config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kindles, only: [:new, :create, :edit, :update]
  resources :images do
    member do
      get :share # ie. generate image
      get :image # i.e. show page for img
    end
  end
  resources :highlights, only: [:index, :edit, :update, :destroy] do
    resources :images, only: :create
    collection do
      # get 'flashcards:id', to: 'highlights#flashcards', as: :flashcards
      get :flashcards
      get :favorites
      get :tags
      put :tags
      get :all_tags
    end
    member do
      get :fav
      put :fav
      get :unfav
      put :unfav
      get :export
      get :destroy_file
    end
  end
  resources :sources, only: [:show] do
    member do
      get :export_book
      get :destroy_file
      get :export_all
    end
    collection do
      get :books
      get :articles
      get :library
      get :export_many
    end
  end
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :highlights, dependent: :destroy
  has_one_attached :photo
  validates :title, :category, presence: :true
  validates :category, inclusion: { in: %w(book article) }
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :export_book, :export_all]
  after_action :destroy_file, only: [:export_many, :export_all]

  def show
  end

  def export_book
  end

  def export_many
    highlights = params[:highlights]
    if highlights.nil?
      flash[:notice] = 'Please select highlights!'
      redirect_back(fallback_location: 'pages#home')
    else
      highlights.map!(&:to_i)
                .sort!
                .map!{|h| Highlight.find(h)}

      source = highlights.first.source
      generate_file(source, highlights)
    end
  end

  def export_all
    generate_file(@source, @source.highlights.order(page: :asc))
  end

  def library
    if params[:select]
      if params[:select] == '2' # author
        @books = current_user.sources.where(category: 'book').includes(:author).joins(:author).select("name, split_part(name, ' ', 2) as last_name").order("last_name")
      elsif params[:select] == '3' # title
        @books = current_user.sources.where(category: 'book').includes(:author).order(title: :asc)
      elsif params[:select] == '4' # highlights
        @books = current_user.sources.where(category: 'book').includes(:author).left_joins(:highlights).group(:id).order('COUNT(highlights.id) DESC')
      else
        @books = current_user.sources.where(category: 'book').includes(:author).order(created_at: :desc)
      end
    else
      @books = current_user.sources.where(category: 'book').includes(:author).order(created_at: :desc)
    end
  end

  def articles
    if params[:select_a]
      if params[:select_a] == '2' # author
        @articles =  current_user.sources.where(category: 'article').includes(:author).joins(:author).select("name, split_part(name, ' ', 2) as last_name").order("last_name")
      elsif params[:select_a] == '3' # title
        @articles = current_user.sources.where(category: 'article').includes(:author).order(title: :asc)
      elsif params[:select_a] == '4' # highlights
        @articles = current_user.sources.where(category: 'article').includes(:author).left_joins(:highlights).group(:id).order('COUNT(highlights.id) DESC')
      else
        @articles = current_user.sources.where(category: 'article').includes(:author).order(created_at: :desc)
      end
    else
      @articles = current_user.sources.where(category: 'article').includes(:author).order(created_at: :desc)
    end
  end

  private

  def set_source
    @source = Source.find(params[:id])
  end

  def source_params
    params.require(:source).permit(:title, :publishing_year, :category, :author_id, :photo)
  end

  def generate_file(source, highlights)
    directory_name = "public/data"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
    file_path = "#{directory_name}/read_to_remember_#{current_user.id}.md"
    File.open(file_path, "wb+") do |file|
      file << "# #{source.title}\n\n"
      file << "## #{source.author.name}\n\n"
      highlights.each do |h|
        file << "#{h.content}\n\npage: #{h.page}\n\n"
        if !h.my_note.nil? && h.my_note.match(/[^\s]/)
          file << "note: #{h.my_note.strip}\n\n\n\n"
        else
          file << "\n\n"
        end
      end
    end
    sleep(1.8)
    flash[:notice] = 'Yay! Highlights were succsesfully exported!'
    redirect_to source_path(source)
  end

  def destroy_file
    sleep(3)
    file_path = "public/data/read_to_remember_#{current_user.id}.md"
    File.open(file_path, "w+") { |file| file << "" }
  end
end

app/views/sources/_books.html.erb
<div style="position: fixed; z-index:900; top: 0vh; width: 100%; padding: 5px 0;background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">
  <div class="nav-filter" style="padding-left: 23px; padding-top: 20px;"> <!-- books -->
    <div style="border-radius: 24px; margin-bottom: 10px; color: white;">
      <%= form_tag library_sources_path, :method => "get" do %>
        <%= select_tag :select, options_for_select([["Sort by Date", 1], ["Sort by Author", 2], ["Sort by Title", 3], ["Sort by Highlights", 4]], selected: params[:select]), {class: 'filter-input', onchange: "this.form.submit();"} %>
      <% end %>
    </div>
  </div>
</div>

<!--<small style="color:white;">My Books(<%#= books.count %>)</small>-->
<div class="container" style="padding-bottom: 10px; padding-top: 19vh;min-height: 100vh;">
  <div class="row justify-content-sm-center;">
    <% books.each do |book| %>
      <div class="card-source">
        <div style="display:flex; justify-content: space-between; width: 308px;">
          <% if book.photo.present? %>
            <div>
              <%= link_to source_path(book) do %>
                <%= cl_image_tag book.photo.key, height: 108, width: 80, crop: :fill, class: "cover" %>
              <% end %>
            </div>
          <% end %>
          <div class="text">
            <p><strong><%= link_to book.title, source_path(book) %></strong></p>
            <h6 style="color: #797C80;"><%= book.author.name %></h6>
            <p><%= pluralize book.highlights.size, "highlight" %></p>
            <!--
            <div class="export-main">
              <p class="export"><i class="fas fa-file-export"></i></p>
            </div>
          -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sources/_navigation.html.erb
<div id="sourceNavigation" style="position:fixed; display:flex; justify-content: flex-start; top:9.7vh; width: 100%; padding-top: 9px; padding-bottom: 9px; z-index:1000; background: linear-gradient(180deg, #4013a2 0%, #25265b 100%);">
  <%= link_to "Books", library_sources_path, class: "link-library books" %>
  <%= link_to "Articles", articles_sources_path, class: "link-library articles" %></p>
  <%= link_to "My Tags", all_tags_highlights_path, class: "link-library tag" %></p>
</div>

app/views/sources/articles.html.erb
<div style="position: fixed; z-index:900; top: 0vh; width: 100%; padding: 5px 0;background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">
  <div class="nav-filter" style="padding-left: 23px; padding-top: 20px;"> <!-- articles -->
    <div style="border-radius: 24px; margin-bottom: 10px; color: white;">
    <%= form_tag articles_sources_path, :method => "get" do %>
      <%= select_tag :select_a, options_for_select([["Sort by Date", 1], ["Sort by Author", 2], ["Sort by Title", 3], ["Sort by Highlights", 4]], selected: params[:select_a]), {class: 'filter-input', onchange: "this.form.submit();"} %>
 <!--     <#%= submit_tag "Sort", :name => nil, style: "opacity: 70%; display-flex; background-color:rgba(126,68,255,1); border:none; font-weight: 600; margin-left: 10px; padding: 2px 17px; color: white; border-radius: 24px;" %>
    -->
    <% end %>


    </div>
  </div>
</div>
<%= render 'sources/navigation' %>

<div class="container" style="padding-bottom: 10px; padding-top: 19vh;min-height: 100vh;">
  <div class="row justify-content-sm-center;">
    <% @articles.each do |article| %>
      <div class="card-source">
        <div style="display:flex; justify-content: space-between; width: 308px;">
          <% if article.photo.present? %>
            <div>
              <%= link_to source_path(article) do %>
                <%= cl_image_tag article.photo.key, height: 108, width: 80, crop: :fill, class: "cover" %>
              <% end %>
            </div>
          <% end %>
          <div class="text">
            <p><strong><%= link_to article.title, source_path(article) %></strong></p>
            <h6 style="color: #797C80;"><%= article.author.name %></h6>
            <p><%= pluralize article.highlights.size, "highlight" %></p>
            <!--
            <div class="export-main">
              <p class="export"><i class="fas fa-file-export"></i></p>
            </div>
          -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sources/export_book.html.erb
<div class="container" style="position:fixed; z-index:900; width: 100%;top: 0vh; padding:0;background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">

    <div class="card-s">
      <div style="display:flex; justify-content: space-between; width: 100%;">
        <% if @source.photo.present? %>
          <div>
            <%= cl_image_tag @source.photo.key, height: 84, width: 70, crop: :fill, class: "cover-s" %>
          </div>
        <% end %>
        <div class="text-s">
          <h6 style="margin-top:7px;"><%= @source.title %></h6>
          <span style="color: #B6B4B5;font-size: 12px;"><%= @source.author.name %></span>
          <br>
          <span><%= link_to 'Cancel', :back, style: "color: #fff; font-size: 16px;"%> | </span>
          <span><%= link_to 'Export all', export_all_source_path, id: 'ex-all', style: "color: #fff; font-size: 16px;" %></span>
        </div>
      </div>
    </div>

</div>

<%= link_to "download",  asset_path("/data/read_to_remember_#{current_user.id}.md"), download: "#{@source.title.gsub(' ', '_')}.md", id: 'dwnld-all', style: 'display: none;' %>

<div class="container" style="padding-top:16vh; min-height:100vh; margin-bottom: 56px;">


  <%= form_tag export_many_sources_path, class: 'row id-form', :method => "get" do %>
    <% @source.highlights.order(page: :asc).each do |h| %>
    <div class='col-1'>
      <p style='position: absolute; top: 50%; transform: translate(0, -50%);'><%= check_box_tag 'highlights[]', h.id, false, class: 'rounded' %></p>
    </div>
    <div class='col-11'>
      <div class="card" id='<%= "note-#{h.id}" %>'>
        <p><%= h.content %></p>
        <p class="page">Page <%= h.page %></p>
        <!-- -->
        <% if h.my_note.present? %>
          <div class="card-note" style="width: 100%; padding-bottom: 12px;">
            <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
            <p style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto"><%= h.h_note %></p>
            <div style="display: flex; flex-wrap: wrap;">
              <p style="font-size: 12px; font-weight: 300; font-height:0; color: #13154E; font-family: Roboto;"><% h.tag_list.each do |t| %></p>
              <p style="font-weight: 300; padding-left: .5vw; font-size:12px; margin:0;"><%= link_to "#{t}", tags_highlights_path(t), style: "color:#25265B;"%></p>
              <% end %>
            </div>
          </div>
        <% end %>
<!--
        <div id="<%= h.id %>" style="display: none;"></div>

        <div class="icons">
          <div class="sent">
            <#% if current_user.favorited?(h) %>
              <p>
                <#%= link_to unfav_highlight_path(h), method: :put, remote: true  do %>
                  <i onclick=changeHeart(this) title='Unfavorite' class="fas fa-heart" style="font-size:16px;"></i>
                <#% end %>
              </p>
            <#% else %>
              <p>
                <#%= link_to fav_highlight_path(h), method: :put, remote: true  do %>
                  <i onclick=changeHeart(this) title='Favorite' class="far fa-heart" style="font-size:16px;"></i>
                <#% end %>
              </p>
            <#% end %>

              <p>
                <#%= link_to edit_highlight_path(h), remote: true do %>
                  <i class="fas fa-pen" title='Write/update note' style="font-size:16px;color:#AAAAAA;"></i>
                <#% end %>
              </p>

            <p>
              <#%= link_to export_highlight_path(h), remote: true do %>
                <i class="fas fa-paper-plane" title='Export' style="font-size:16px;color:#AAAAAA;"></i>
              <#% end %>
            </p>
          </div>
          <div class="delete">
            <p><#%= link_to h, method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="far fa-trash-alt" title='Delete' style="font-size:16px;color:#AAAAAA;"></i></p>
            <#% end %>
          </div>
        </div>

      -->
      </div>
    </div>
    <% end %>
    <%= submit_tag "Submit", class: 'btn btn-primary download' %>
    <% end %>

</div>

<div id='loadDiv' style='display: none; text-align: center;'>
  <div class='line-load'></div>
  <div class='progress-load'></div>
  <p style='padding-top: 12px; color: #efefefef;'>loading</p>
</div>

app/views/sources/library.html.erb
<%= render 'sources/navigation' %>
<%= render 'sources/books', books: @books %>

app/views/sources/show.html.erb
<div class="container" style="position:fixed; z-index:900; width: 100%;top: 0vh; padding:0;background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">
  <div class="card-s">
    <div style="display:flex; justify-content: space-between; width: 100%;">
      <% if @source.photo.present? %>
        <div>
          <%= cl_image_tag @source.photo.key, height: 84, width: 70, crop: :fill, class: "cover-s" %>
        </div>
      <% end %>
      <div class="text-s">
        <h6 style="margin-top:7px;"><%= @source.title %></h6>
        <span style="color: #B6B4B5;font-size: 12px;"><%= @source.author.name %></span>
        <% if @source.highlights.present? %>
          <p><%= link_to 'Export', export_book_source_path, style: "color: #fff; font-size: 16px;"%></p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container" style="padding-top:16vh; min-height:100vh; margin-bottom: 72px;">
  <div class="container" style="margin: 15px;">
  <div class="row">
    <% @source.highlights.includes(:taggings).order(page: :asc).each do |h| %>
      <div class="card card-adjusted" id='card-<%= h.id %>'>
        <div class='my-nodes'></div>

        <div id='image-<%= h.id %>'>
          <div id='<%= "note-#{h.id}" %>'>
            <p><%= h.content %></p>
            <p class="page">Page <%= h.page %></p>
            <!-- note and tags in one line! -->
            <% if h.my_note.present? %>
              <div class="card-note" style="width: 100%; padding-bottom: 12px;">
                <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
                <div style="display: flex; flex-wrap: wrap;">
                  <p style="">
                    <% h.my_note.split(' ').each do |w| %>
                      <% if h.tag_list.include?(w) %>
                        <span>
                          <%= link_to "#{w}", tags_highlights_path(w), style: "margin: 0, 2px; font-family: Roboto; font-size: 16px; font-weight: 300; font-height:0; color:#25265B;"%>
                        </span>
                      <% else %>
                        <span style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto;"><%= w %> </span>
                      <% end %>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>
            <div id="<%= h.id %>" style="display: none;"></div>
          </div>
        </div>
        <%= link_to "download", asset_path("/data/read_to_remember_#{current_user.id}.md"), id: 'dwnld', style: 'display: none;' %>
        <div class="icons">
          <div class="sent">
            <% if current_user.favorited?(h) %>
              <p>
                <%= link_to unfav_highlight_path(h), method: :put, remote: true  do %>
                  <i title='Unfavorite' class="fas fa-heart" style="font-size:16px;color:#555555;"></i>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to fav_highlight_path(h), method: :put, remote: true  do %>
                  <i title='Favorite' class="far fa-heart" style="font-size:16px;color:#aaa;"></i>
                <% end %>
              </p>
            <% end %>
            <p>
              <%= link_to edit_highlight_path(h), remote: true do %>
                <i class="fas fa-pen" title='Write/update note' style="font-size:16px;color:#AAAAAA;"></i>
              <% end %>
            </p>
             <p>
                <%= link_to export_highlight_path(h), remote: true do %>
                  <i id='e-<%= h.id %>' class="fas fa-paper-plane" title='Export' style="font-size:16px;color:#AAAAAA;"></i>
                <% end %>
              </p>

              <p class='my-btns' data-card-id='<%= h.id %>'>
               <i class="fas fa-share-alt" style="font-size:16px;color:#AAAAAA;"></i>
              </p>

            </div>
            <div class="delete">
              <p><%= link_to h, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
                <i class="far fa-trash-alt" title='Delete' style="font-size:16px;color:#AAAAAA;"></i></p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id='myAlert' class="alert alert-warning alert-dismissible fade show m-1" style='display:none;'>
  Yay! Highlight was succsesfully exported!
  <button type="button" class="close" id='closeBtn'>
    <span aria-hidden="true">&times;</span>
  </button>
</div>