config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kindles, only: [:new, :create, :edit, :update]
  resources :images do
    member do
      get :share # ie. generate image
      get :image # i.e. show page for img
    end
  end
  resources :highlights, only: [:index, :edit, :update, :destroy] do
    resources :images, only: :create
    collection do
      # get 'flashcards:id', to: 'highlights#flashcards', as: :flashcards
      get :flashcards
      get :favorites
      get :tags
      put :tags
      get :all_tags
    end
    member do
      get :fav
      put :fav
      get :unfav
      put :unfav
      get :export
      get :destroy_file
    end
  end
  resources :sources, only: [:show] do
    member do
      get :export_book
      get :destroy_file
      get :export_all
    end
    collection do
      get :books
      get :articles
      get :library
      get :export_many
    end
  end
end

app/models/highlight.rb
class Highlight < ApplicationRecord
  belongs_to :user
  belongs_to :source
  has_many :images, dependent: :destroy
  validates :content, presence: true
  validates :page, presence: true
  acts_as_taggable_on :tags
  acts_as_favoritable
  before_save :set_note_and_tags
  # pg_search => searching through association
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [:content, :my_note],
  associated_against: {
    source: [:title]
  },
  using: {
    tsearch: { prefix: true }
  }

  private

  def set_note_and_tags
    if my_note
      note = self.my_note.split(" ")
      tags = []
      my_n = self.my_note.split(" ")
      reg = /^#.+/
      note.each do |w|
        if w.match(reg)
          my_n.delete(w)
          tags << w
        end
      end
      tags.uniq!
      self.h_note = my_n.join(" ")
      self.tag_list = "#{tags.join(", ")}"
    end
  end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:edit, :update, :destroy, :fav, :unfav, :export]
  before_action :set_tag, only: :tags
  respond_to :html, :js

  # search here
  def index
    if params[:query].present?
      @query = params[:query]
      @highlights = current_user.highlights.includes(:source, :taggings,  source: :author).global_search(@query)
      @count = @highlights.size
    else
      @highlights = []
    end
  end

  def edit
  end

  def update
    if @highlight.update(note_tag_param)
      respond_to :js
    end
  end

  def destroy # works (except: carousel)
    @highlight.destroy
    # respond_to :js
    # flash[:notice] = 'Highlight was succsesfully removed!'
  end

  def fav # works!
    current_user.favorite(@highlight)
    #redirect_back(fallback_location: 'pages#home')
    # respond_to do |format|
    #   format.js
    # end
  end

  def unfav # works!
    current_user.unfavorite(@highlight)
    #redirect_back(fallback_location: 'pages#home')
    # respond_to do |format|
    #  format.js
    # end
  end

  def export # works!
    # generate file:
    directory_name = "public/data"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
    file_path = "#{directory_name}/read_to_remember_#{current_user.id}.md"
    File.open(file_path, "w+") do |file|
      file << "# #{@highlight.source.title}\n\n"
      file << "## #{@highlight.source.author.name}\n\n"
      file << "#{@highlight.content}\n\n"
      file << "page: #{@highlight.page}\n\n"
      if !@highlight.my_note.nil? && @highlight.my_note.match(/[^\s]/)
        file << "note: #{@highlight.my_note}"
      end
    end
    # destroy file
    sleep(2)
    File.open(file_path, "w+") { |file| file << "" }
  end

  def flashcards
    @flashcards = current_user.flashcards.includes(:taggings, source: :author)
  end

  def favorites
    @highlights = current_user.highlights.includes(:taggings, source: :author).joins('INNER JOIN favorites on highlights.id = favorites.favoritable_id').order('favorites.created_at desc')
  end

  def tags
    @tagged_highlights = current_user.highlights.includes(:taggings, source: :author).tagged_with(["#{@tag}"], :any => true)
  end

  def all_tags
    if params[:select_t]
      if params[:select_t] == '2' # amount
        @all_tags = current_user.highlights.includes(:taggings, source: :author).tag_counts_on(:tags).order(taggings_count: :desc)
      else
        @all_tags = current_user.highlights.includes(:taggings, source: :author).tag_counts_on(:tags).order(created_at: :desc)
      end
    else
      @all_tags = current_user.highlights.includes(:taggings, source: :author).tag_counts_on(:tags).order(created_at: :desc)
    end
  end

  private

  def set_highlight
    @highlight = Highlight.find(params[:id])
  end

  def set_tag
    @tag = params[:format]
  end

  def highlight_params
    params.require(:highlight).permit(:content, :page, :favorite, :source_id, :user_id, :tag_list)
  end

  def note_tag_param
    params.require(:highlight).permit(:h_note, :my_note, :tag_list)
  end
end

app/views/highlights/_edit.html.erb
<div class="card" style="width: 86%;">
  <%= simple_form_for([@highlight], remote: true) do |f| %>
 <!-- trigger on enter: <#%= hidden_field_tag :authenticity_token, form_authenticity_token %> -->
    <%= f.input :my_note, label: false %>
    <%= f.submit "Save", style: "font-size:12px;background-color:rgba(76,68,255,.8); border:none; font-weight:bold; padding:4px 8px; color: white; border-radius: 16px;" %>
  <% end %>
</div>

<script>
// trigger on enter => works with redirect_back in cntrl but! no remote
/*
  document.getElementById('highlight_my_note').addEventListener('keyup', triggerSubmit);
  function triggerSubmit(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      document.querySelector('.simple_form.edit_highlight').submit();
    }
  }
*/

document.querySelector('.simple_form.edit_highlight').addEventListener('submit', moveCarousel);

function moveCarousel() {
  const location = window.location.href; //change location for production
  const regexp = /#[0-9]+/
  const myLocation = location.replace(regexp, '');
  console.log(myLocation);
  if (myLocation  == `http://localhost:3000/highlights/flashcards`) {
    const items = document.getElementById('items');
    const myCarousel = document.getElementById('slider');

    const lastInx = document.getElementById('lastInx');
    const index = parseInt(lastInx.innerText, 10);

    const lastBools = document.getElementById('lastBools');
    const boolArr = lastBools.innerText.replace(/,+/g, ' ').split(' ');

    console.log(boolArr);
    console.log('edit: ' + index);

    let myBool = Array.prototype.map.call(boolArr, function(a) { return JSON.parse(a) });

    // run carousel again
    // overwrite initCarousel...
    runCarousel(myCarousel, items, 0, myBool);

   } else {
     // do nothing
  }
}

// wip

function runCarousel(wrapper, items, index, myBool) {
  var posX1 = 0,
      posX2 = 0,
      posInitial,
      posFinal,
      threshold = 100,
      slides = items.getElementsByClassName('carousel-card'),
      slidesLength = slides.length,
      slideSize = items.getElementsByClassName('carousel-card')[0].offsetWidth,
      firstSlide = slides[0],
      lastSlide = slides[slidesLength - 1],
      lastSlide = slides[slidesLength - 1],
      allowShift = true;


  wrapper.classList.add('loaded');

  // Mouse and Touch events
  items.addEventListener('mousedown', dragStart);
  // Touch events
  items.addEventListener('touchstart', dragStart);
  items.addEventListener('touchend', dragEnd);
  items.addEventListener('touchmove', dragAction);
  // Transition events
  items.addEventListener('transitionend', checkIndex);

  //vars
  let ids = Array.prototype.map.call(slides, function(a) { return a.id.replace(/(false|true)-/, '') });
  ids.shift();
  console.log(ids)

  console.log(myBool)

  const favLink = document.getElementById('fav');
  const unfavLink = document.getElementById('unfav');
  const editLink = document.getElementById('edit');
  const exportLink = document.getElementById('export');
  const delLink = document.getElementById('del');

  // init links
  if (myBool[index]) {
    unfavLink.href = `${ids[index]}/unfav`;
    favLink.style.display = 'none';
    unfavLink.style.display = 'inherit';
  } else {
    favLink.href = `${ids[index]}/fav`;
    unfavLink.style.display = 'none';
    favLink.style.display = 'inherit';
  }


  editLink.href = `${ids[index]}/edit`;
  exportLink.href = `${ids[index]}/export`;
  delLink.href = `${ids[index]}/`;


  function dragStart (e) {
    e = e || window.event;
    e.preventDefault();
    posInitial = items.offsetLeft;
    console.log('dragstart: ' + posInitial);

    if (e.type == 'touchstart') {
      posX1 = e.touches[0].clientX;
    } else {
      posX1 = e.clientX;
      document.onmouseup = dragEnd;
      document.onmousemove = dragAction;
    }
  }

  function dragAction (e) {
    e = e || window.event;

    if (e.type == 'touchmove') {
      posX2 = posX1 - e.touches[0].clientX;
      posX1 = e.touches[0].clientX;

    } else {
      posX2 = posX1 - e.clientX;
      posX1 = e.clientX;
    }
    items.style.left = (items.offsetLeft - posX2) + "px";
  }

  function dragEnd (e) {
    posFinal = items.offsetLeft;
    if (posFinal - posInitial < -threshold) {
      shiftSlide(1, 'drag');
    } else if (posFinal - posInitial > threshold) {
      shiftSlide(-1, 'drag');
    } else {
      items.style.left = (posInitial) + "px";
    }

    document.onmouseup = null;
    document.onmousemove = null;
  }

  function shiftSlide(dir, action) {
    items.classList.add('shifting');

    if (allowShift) {
      if (!action) { posInitial = items.offsetLeft; }

      if (dir == 1) {
        items.style.left = (posInitial - slideSize) + "px";
        index++;
      } else if (dir == -1) {
        items.style.left = (posInitial + slideSize) + "px";
        index--;
      }
    };

    allowShift = false;
  }

  function checkIndex() {  // do smtng here
    items.classList.remove('shifting');
    console.log(myBool);
    console.log(ids);
    console.log(index);
    //console.log(ids[index]);


    if (index == -1) {
      items.style.left = -(slidesLength * slideSize) + "px";
      index = slidesLength - 1;
    }

    if (index == slidesLength) {
      items.style.left = -(1 * slideSize) + "px";
      index = 0;
    }

    allowShift = true;

    //update links
      if (myBool[index]) {
        unfavLink.href = `${ids[index]}/unfav`;
        favLink.style.display = 'none';
        unfavLink.style.display = 'inherit';
      } else {
        favLink.href = `${ids[index]}/fav`;
        unfavLink.style.display = 'none';
        favLink.style.display = 'inherit';
      }

      editLink.href = `${ids[index]}/edit`;
      exportLink.href = `${ids[index]}/export`;
      delLink.href = `${ids[index]}/`;
  }

  favLink.addEventListener('click', changeHeart);
  unfavLink.addEventListener('click', changeHeart);

  function changeHeart() {

    if (myBool[index] === true) {
      myBool[index] = false;
      favLink.style.display = 'inherit';
      unfavLink.style.display = 'none';
    } else {
      myBool[index] = true;
      favLink.style.display = 'none';
      unfavLink.style.display = 'inherit';
    }
    console.log(myBool);
  }

  editLink.addEventListener('click', makeItWork);

  function makeItWork() {
    console.log('do smtng');

    // stop carousel do be able to write a note (works but not on last slide :/)
    items.removeEventListener('mousedown', dragStart);
    items.removeEventListener('touchstart', dragStart);
    items.removeEventListener('touchend', dragEnd);
    items.removeEventListener('touchmove', dragAction);

   // *make it run again on submit

  }

  exportLink.addEventListener('click', showAlert);

  function showAlert() {
    setTimeout(function(){
      document.getElementById(`dwnld-${ids[index]}`).click();
      document.getElementById('myAlert').style.display = 'inherit';
      document.getElementById('clsBtn').addEventListener('click', closeIt);
    }, 900 );

    setTimeout(function(){
      document.getElementById('myAlert').style.display = 'none';
    }, 4000);
  }

  function closeIt() {
    document.getElementById('myAlert').style.display = 'none';
  }

}

</script>

app/views/highlights/_exit.html.erb
<%= link_to library_sources_path do %>
  <i class="fas fa-times exit-icon"></i>
<% end %>

app/views/highlights/_highlight.html.erb
<div id='<%= "note-#{@highlight.id}" %>'>
  <p><%= @highlight.content %></p>
  <p class="page">Page <%= @highlight.page %></p>
  <!-- note and tags in one line! -->
  <% if @highlight.my_note.present? %>
    <div class="card-note" style="width: 100%; padding-bottom: 12px;">
      <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
      <div style="display: flex; flex-wrap: wrap;">
        <p style="">
          <% @highlight.my_note.split(' ').each do |w| %>
            <% if @highlight.tag_list.include?(w) %>
              <span>
                <%= link_to "#{w}", tags_highlights_path(w), style: "margin: 0, 2px; font-family: Roboto; font-size: 16px; font-weight: 300; font-height:0; color:#25265B;"%>
              </span>
            <% else %>
              <span style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto;"><%= w %> </span>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
  <div id="<%= @highlight.id %>" style="display: none;"></div>
</div>

app/views/highlights/_highlight_card.html.erb
<div class="container" style="margin: 15px;">
  <div class="row">
    <% highlights.each do |h| %>
      <div class="card card-adjusted" id='card-<%= h.id %>'>
        <div class='my-nodes'></div>
        <div id='image-<%= h.id %>'>
          <h3 style="font-size: 12px; font-weight: bold; font-family: Spartan"><%= link_to h.source.title, source_path(h.source) %></h3>
          <h5 style="color: #797C80; margin-bottom:25px; font-size: 12px; font-weight: 400;"><%= h.source.author.name %></h5>
          <!-- render part -->
          <div id='<%= "note-#{h.id}" %>'>
            <p><%= h.content %></p>
            <p class="page">Page <%= h.page %></p>
            <% if h.my_note.present? %>
              <div class="card-note" style="width: 100%; padding-bottom: 12px;">
                <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
                <div style="display: flex; flex-wrap: wrap;">
                  <p style="">
                    <% h.my_note.split(' ').each do |w| %>
                      <% if h.tag_list.include?(w) %>
                        <span>
                          <%= link_to "#{w}", tags_highlights_path(w), style: "margin: 0, 2px; font-family: Roboto; font-size: 16px; font-weight: 300; font-height:0; color:#25265B;"%>
                        </span>
                      <% else %>
                        <span style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto;"><%= w %> </span>
                      <% end %>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>
            <div id="<%= h.id %>" style="display: none;"></div>
          </div>
        </div>
        <%= link_to "download", asset_path("/data/read_to_remember_#{current_user.id}.md"), id: 'dwnld', style: 'display: none;' %>
        <div class="icons">
          <div class="sent">
            <% if current_user.favorited?(h) %>
              <p>
                <%= link_to unfav_highlight_path(h), method: :put, remote: true do %>
                  <i id='f-<%= h.id %>' title='Unfavorite' class="fas fa-heart" style="font-size:16px;color:#555555;" ></i>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to fav_highlight_path(h), method: :put, remote: true do %>
                  <i title='Favorite' class="far fa-heart" style="font-size:16px;color:#aaa"></i>
                <% end %>
              </p>
            <% end %>
            <p>
              <%= link_to edit_highlight_path(h), remote: true do %>
                <i class="fas fa-pen edit-icon" title='Write/update note' data-id="<%= h.id %>" style="font-size:16px;color:#AAAAAA;"></i>
              <% end %>
            </p>
            <p>
              <%= link_to export_highlight_path(h), remote: true do %> <!-- improve this one :export -->
                <i id='e-<%= h.id %>' class="fas fa-paper-plane" title='Export' style="font-size:16px;color:#AAAAAA;"></i>
              <% end %>
            </p>
            <p class='my-btns' data-card-id='<%= h.id %>'>
              <i class="fas fa-share-alt" title='Share as image' style="font-size:16px;color:#AAAAAA;"></i>
            </p>
          </div>
          <div class="delete">
            <p><%= link_to h, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
              <i class="far fa-trash-alt" title='Delete' style="font-size:16px;color:#AAAAAA;"></i></p>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

<div id='myAlert' class="alert alert-warning alert-dismissible fade show m-1" style='display:none;'>
  Yay! Highlight was succsesfully exported!
  <button type="button" class="close" id='closeBtn'>
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/highlights/_icons.html.erb
<div class="icons" style='position: absolute; top: 86%; left:50%; transform:translateX(-50%);'>
  <p>
    <%= link_to unfav_highlight_path(h), id: "unfav",  method: :put, remote: true  do %>
      <i  title='Unfavorite' class="fas fa-heart flashcard-button" style='color:#555555'></i>
    <% end %>
  </p>
  <p>
    <%= link_to fav_highlight_path(h), id: "fav", method: :put, remote: true  do %>
      <i title='Favorite' class="far fa-heart flashcard-button" style='color:#aaa'></i>
    <% end %>
  </p>
  <p>
    <%= link_to edit_highlight_path(h), id: "edit", remote: true do %>
      <i class="fas fa-pen flashcard-button" title='Write/update note'></i>
    <% end %>
  </p>
  <p>
    <%= link_to export_highlight_path(h), id: "export", remote: true do %>
      <i class="fas fa-paper-plane flashcard-button" title='Export'></i>
    <% end %>
  </p>
  <p id='img-btn'>
    <i class="fas fa-share-alt flashcard-button" title='Share as image'></i>
  </p>
<!-- remove this option -->
<!--
  <div class="delete">
    <p>
      <%#= link_to h, method: :delete, data: {confirm: "Are you sure?"}, id: "del", remote: true do %>
        <i class="far fa-trash-alt flashcard-button" title='Delete'></i>
      <#% end %>
    </p>
  </div> -->
</div>

<div id='myAlert' class="alert alert-warning alert-dismissible fade show m-1" style='display:none;'>
  Yay! Highlight was succsesfully exported!
  <button type="button" class="close" id='clsBtn'>
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/highlights/all_tags.html.erb
<div style="position: fixed; z-index:900; top: 0vh; width: 100%; padding: 5px 0;background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">
  <div class="nav-filter" style="padding-left: 23px; padding-top: 20px;"> <!-- tags -->
    <div style="border-radius: 24px; margin-bottom: 10px; color: white;">
    <%= form_tag all_tags_highlights_path, :method => "get" do %>
      <%= select_tag :select_t, options_for_select([["Sort by Date", 1], ["Sort by Amount", 2]], selected: params[:select_t]), {class: 'filter-input t', onchange: 'this.form.submit();'} %>
    <% end %>
    </div>
  </div>
</div>
<%= render 'sources/navigation' %>
<div class="container" style="padding-bottom: 20px; padding-top: 142px; min-height: 100vh;">
  <div style="display:flex; flex-wrap: wrap;">
    <% @all_tags.each do |t| %>
    <% font_size= 'font-size: 16px;' if t.taggings_count == 2 %>
    <% font_size= 'font-size: 20px;' if t.taggings_count == 3 %>
    <% font_size= 'font-size: 24px;' if t.taggings_count == 4 %>
    <% font_size= 'font-size: 28px;' if t.taggings_count == 5 %>
    <% font_size= 'font-size: 32px;' if t.taggings_count == 6 %>
     <p class="tags" style="border-style: solid; border-width: 0; border-radius: 30px; font-size: 15px; padding: 1vh 2vh; color: white; background-color: #7E44FF; font-weight: bolder; margin-left: 1vh; opacity: 70%; box-shadow: 0px 4px 4px rgba(8, 13, 60, 0.09);"><%= link_to t.name, tags_highlights_path(t.name), class: "tag", style: "color: white; padding-right: 1vh; font-size: 15px; #{font_size}"%>(<%= t.taggings_count %>)</p>
    <% end %>
  </div>
</div>

app/views/highlights/destroy.js.erb
document.getElementById('card-<%= @highlight.id %>').remove();

app/views/highlights/edit.js.erb
$('#<%= @highlight.id %>').html("<%= j (render 'highlights/edit') %>");
$('#<%= @highlight.id %>').slideDown(350);

app/views/highlights/favorites.html.erb
<div class="container" style="min-height: 100vh;">
  <%= render 'highlights/highlight_card', highlights: @highlights %>
</div>

app/views/highlights/flashcards.html.erb
<%= render 'exit'%>
<div id='node' class='my-nodes'></div>
<!-- vanilla -->
<% if @flashcards.present? %>
  <div id="slider" class="slider"style='position:absolute; left:50%; transform:translateX(-50%); background: transparent; padding: 4px; height: 500px; width: 300px;'>
    <div class="wrapper" style='background: #fff; border-radius: 16px; overflow: hidden; position: relative;box-shadow: 0px 2px 8px 4px rgba(8, 13, 60, 0.3);'>
      <div id='items' class="items" style='width: 10000px;position: relative;top:0; left: -300px;'>
        <% @flashcards.each do |h| %>
          <div class="carousel-card" id='<%= current_user.favorited?(h) %>-<%= h.id %>'> <!--id="card-<%#= h.id %>">-->
            <div style="float: left;"><%= @flashcards.index(h) + 1 %></div>
             <div id='image-f-<%= h.id %>'>
              <div class="flashcard-text">
                <h3 style="font-size: 12px; font-weight: bold; font-family: Spartan; padding-top: 24px;"><%= h.source.title %></h3>
                <h5 style="color: #797C80; margin-bottom:25px; font-size: 12px; font-weight: 400;"><%= h.source.author.name %></h5>
              </div>
              <div id='<%= "note-#{h.id}" %>'>
                <p style="margin-bottom: 20px;"><%= h.content %></p>
                <p class="page">Page <%= h.page %></p>
                <% if h.my_note.present? %>
                  <div class="card-note" style="width: 100%; padding-bottom: 12px;">
                    <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
                    <p style="">
                      <% h.my_note.split(' ').each do |w| %>
                        <% if h.tag_list.include?(w) %>
                          <span>
                            <%= link_to "#{w}", tags_highlights_path(w), style: "margin: 0, 2px; font-family: Roboto; font-size: 16px; font-weight: 300; font-height:0; color:#25265B;"%>
                          </span>
                        <% else %>
                          <span style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto;"><%= w %> </span>
                        <% end %>
                      <% end %>
                    </p>
                  </div>
                <% end %>
               <div id="<%= h.id %>" style="display: none;"></div>
              </div>
            </div>
            <%= link_to "download",  asset_path("/data/read_to_remember_#{current_user.id}.md"), download: "#{h.source.title.gsub(' ', '_')}_#{h.page}.md", id: "dwnld-#{h.id}", style: 'display: none;' %>
          </div>
        <% end %>
      </div>
    </div>
    <div id='lastInx' style='display: none;'></div>
    <div id='lastBools' style='display: none;'></div>

  </div>

  <%= render 'icons', h: @flashcards.first %>
<% end %>
<!-- end of vanilla -->

<!-- flickity -->
<!--
<#% if @flashcards.present? %>
  <div class="carousel" id='myCarousel' data-initial-card="<#%= @highlight.id if @highlight %>">
    <#% @flashcards.each do |h| %>
      <div class="flashcard transparent-container carousel-cell" id="carousel-cell<#%= @flashcards.index(h) + 1 %>" data-card-id="<#%= @flashcards.index(h) + 1 %>-<#%= current_user.favorited?(h) %>-<#%= h.id %>">
        <div class="flashcard-text">
          <h3 style="font-size: 12px; font-weight: bold; font-family: Spartan"><#%= link_to h.source.title, source_path(h.source) %></h3>
          <h5 style="color: #797C80; margin-bottom:25px; font-size: 12px; font-weight: 400;"><#%= h.source.author.name %></h5>
        </div>
        <!- render part --> <!--
        <div id='<#%= "note-#{h.id}" %>'>
          <p><#%= h.content %></p>
          <p class="page">Page <#%= h.page %></p>
          <!- note and tags in one line! --> <!--
          <#% if h.my_note.present? %>
            <div class="card-note" style="width: 100%; padding-bottom: 12px;">
              <p style="font-weight: 600; color: #898AA6; font-size:12px; margin: 0;">Notes</p>
              <div style="display: flex; flex-wrap: wrap;">
                <p style="">
                  <#% h.my_note.split(' ').each do |w| %>
                    <#% if h.tag_list.include?(w) %>
                      <span>
                        <#%= link_to "#{w}", tags_highlights_path(w), style: "margin: 0, 2px; font-family: Roboto; font-size: 16px; font-weight: 300; font-height:0; color:#25265B;"%>
                      </span>
                    <#% else %>
                      <span style="font-weight: 300; font-size:14px; color: #13154E; margin: 0; font-family: Roboto;"><#%= w %> </span>
                    <#% end %>
                  <#% end %>
                </p>
              </div>
            </div>
          <#% end %>
          <div id="<#%= h.id %>" style="display: none;"></div>
        </div>
        <#%= link_to "download", asset_path("/data/read_to_remember_#{current_user.id}.md"), id: "dwnld", style: 'display: none;' %>
      </div>
    <#% end %>
  </div>
<#%= render 'icons', h: @flashcards.first %>
<#% end %>
-->

app/views/highlights/index.html.erb
<div style="z-index:900;top: 0vh;height: 13vh; width:100%;position:fixed; background: linear-gradient(180deg, #25265b 10%, #4013a2 100%);">
  <div style="padding-left: 23px; padding-top:10px;"> <!-- books -->
    <div style="border-radius: 24px; margin-bottom: 20px; padding-top: 15px; color: white;">
      <%= form_tag highlights_path, class: "form-inline-sm search", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control-sm",
          id: 'mySearch',
          placeholder: "What are you looking for?"
        %>
        <% submit_tag "Search", id: 'mySubmit' %>
      <% end %>
      <% if @query %>
        <p style="color: #fff;padding-left: 10px; padding-top: 8px; ">We found <%= pluralize @count, 'result' %> for <strong><%= @query %></strong>.</p>
      <% end %>
    </div>
  </div>
</div>

<div class="container" style="padding-top: 12vh;min-height: 100vh;">
  <%= render 'highlights/highlight_card', highlights: @highlights %>
</div>

<script>
  document.getElementById('mySearch').addEventListener('keyup', triggerSubmit);
  function triggerSubmit(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      document.getElementById('mySubmit').click();
    }
  }
</script>

app/views/highlights/tags.html.erb
<div class="container" style="padding-left: 15px; padding-top: 22px; padding-bottom: 10px;">
  <%= render 'highlights/highlight_card', highlights: @tagged_highlights %>
</div>

app/views/highlights/update.js.erb
$('#note-<%= @highlight.id %>').replaceWith("<%= j (render 'highlights/highlight') %>");